spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_EXTERNAL_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

grpc:
  server:
    port: ${INTERNAL_SERVER_PORT}
    reflection-service-enabled: true

security:
  session:
    ttl: P1D
  jwt:
    secret: ${JWT_SECRET}
    expiration: PT15M
    issuer: auth-service
    audience: auth-client