version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: auth-service/Dockerfile
    container_name: auth_service_app
    ports:
      - "${EXTERNAL_SERVER_PORT}:${INTERNAL_SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_EXTERNAL_PORT: "5432"
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5433}:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  db_data:
