apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  JWT_SECRET: <base64_value>
  POSTGRES_DB: <base64_value>
  POSTGRES_USER: <base64_value>
  POSTGRES_PASSWORD: <base64_value>
  POSTGRES_HOST: <base64_value>

