name: auth-service

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - 'auth-service/**'
      - 'grpc/**'

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Build grpc
        run: mvn -f grpc/pom.xml clean install -DskipTests

      - name: Test auth-service
        run: mvn -f auth-service/pom.xml clean test

  verify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Build grpc
        run: mvn -f grpc/pom.xml clean install -DskipTests

      - name: Verify auth-service
        run: mvn -f auth-service/pom.xml clean verify

  qodana:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [test, verify]
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: true
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: false
          push-fixes: 'none'

  build-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    needs: [test, verify]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: auth-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cvhub.auth-service:latest

